### ISSUE TITLE
where is breakfast config

### ISSUE THREAD

**Issue by zhoutianyi1** [ShangHua-Gao/G2L-search#3]
Hello, in the README, i wonder where i can find breakfast_sp1.json. Thanks!!

**Comment by txyxju1997** [comment]
@zhoutianyi1 I have the same problem with you, can you find the breakfast_sp1.json now? thanks.

**Comment by Hanqer** [comment]
If you want to get the global searched structure 'breakfast_sp1.json', you can find it in the save path of the global search, with name 'iter$ITER_NUMS$_pop[0].json'. You should rename it to 'breakfast_sp1.json'. 
By the way, we will update the pretrained config as soon as possible.

**Comment by gasvn** [comment]
The config of searched dilation rates for breakfast is on https://github.com/ShangHua-Gao/G2L-search/releases/tag/g2l_breakfast_searched_dilation

**Comment by txyxju1997** [comment]
thanks.I have a problem "python main.py --dataset=breakfast --split=1 --action=predict --tmp=results --config=path/to/model_config --pretrain=path/to/model".where should I find config and pretrain files？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShangHua-Gao/G2L-search"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShangHua-Gao/G2L-search] where is breakfast config (#3)





 
If you want to get the global searched structure 'breakfast_sp1.json', you can find it in the save path of the global search, with name 'iter$ITER_NUMS$_pop[0].json'.  By the way, we will update the pretrained config as soon as possible.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gasvn** [comment]
> thanks.I have a problem "python main.py --dataset=breakfast --split=1 --action=predict --tmp=results --config=path/to/model_config --pretrain=path/to/model".where should I find config and pretrain files？

Sorry I missed your comments. After training, these two files are generated. Please let me know if you still cannot find it.
